sudo: required
services:
  - docker

before_install:
  - docker build -t hiteshnatha15/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hiteshnatha15/react-test npm test

after_success:
  - docker build -t hiteshnatha15/multi-client ./client
  - docker build -t hiteshnatha15/multi-nginx ./nginx
  - docker build -t hiteshnatha15/multi-server ./server
  - docker build -t hiteshnatha15/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push hiteshnatha15/multi-client
  - docker push hiteshnatha15/multi-nginx
  - docker push hiteshnatha15/multi-server
  - docker push hiteshnatha15/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-south-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-489154404278"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
